unsupported:
    pattern: /unsupported
    defaults: { _controller: RockITTechgamesBundle:Default:unsupported }

login:
    pattern: /login
    defaults: { _controller: RockITTechgamesBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    path:   /logout

register:
    path:   /register
    defaults: { _controller: RockITTechgamesBundle:Security:register }

rock_it_techgames_homepage:
    pattern:  /
    defaults: { _controller: RockITTechgamesBundle:Default:index }

rock_it_techgames_about:
    pattern:  /about
    defaults: { _controller: RockITTechgamesBundle:Default:about }

rock_it_techgames_newsroom:
    pattern:  /newsroom
    defaults: { _controller: RockITTechgamesBundle:Default:newsroom }

rock_it_techgames_anouncements:
    pattern:  /announcements
    defaults: { _controller: RockITTechgamesBundle:Default:announcements }

game_new:
    pattern:  /game/new
    defaults: { _controller: RockITTechgamesBundle:Game:new }

game_detail:
    pattern:  /game/{gameId}
    defaults: { _controller: RockITTechgamesBundle:Game:detail }

game_detail_reroute:
    pattern:  /game/{gameId}/
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: game_detail
      permanent: true

game_edit:
    pattern:  /game/{gameId}/edit
    defaults: { _controller: RockITTechgamesBundle:Game:edit }

game_delete:
    pattern:  /game/{gameId}/delete
    defaults: { _controller: RockITTechgamesBundle:Game:delete }

game_join:
    pattern:  /game/{gameId}/join
    defaults: { _controller: RockITTechgamesBundle:Game:join }


sponsor_overview:
    pattern:  /sponsors/
    defaults: { _controller: RockITTechgamesBundle:Sponsor:overview }

sponsor_detail:
    pattern:  /sponsors/{sponsorId}
    defaults: { _controller: RockITTechgamesBundle:Sponsor:detail }


teams_overview:
    pattern:  /teams
    defaults: { _controller: RockITTechgamesBundle:Team:overview }

team_create:
    pattern:  /team/create
    defaults: { _controller: RockITTechgamesBundle:Team:create }

team_detail:
    pattern:  /team/{teamId}
    defaults: { _controller: RockITTechgamesBundle:Team:detail }

team_edit:
    pattern:  /team/{teamId}/edit
    defaults: { _controller: RockITTechgamesBundle:Team:edit }

team_delete:
    pattern:  /team/{teamId}/delete
    defaults: { _controller: RockITTechgamesBundle:Team:delete }

team_remove_member:
    pattern:  /team/{teamId}/member/{profileId}/remove
    defaults: { _controller: RockITTechgamesBundle:Team:removeMember }

team_add_member:
    pattern:  /team/{teamId}/member/{profileId}/add
    defaults: { _controller: RockITTechgamesBundle:Team:addMember }


school_detail:
    pattern:  /school/{schoolId}
    defaults: { _controller: RockITTechgamesBundle:School:detail }


admin_overview:
    pattern:  /admin
    defaults: { _controller: RockITTechgamesBundle:Admin:index }


profile_detail:
    pattern:  /profile/{profileId}
    defaults: { _controller: RockITTechgamesBundle:Profile:detail }

user_create:
    pattern:  /user/create
    defaults: { _controller: RockITTechgamesBundle:Profile:create }

user_edit:
    pattern:  /user/{userId}/edit
    defaults: { _controller: RockITTechgamesBundle:Profile:edit }

user_delete:
    pattern:  /user/{userId}/delete
    defaults: { _controller: RockITTechgamesBundle:Profile:delete }


api_users:
    pattern:  /api/user/
    defaults: { _controller: RockITTechgamesBundle:Profile:get }