login:
    pattern: /login
    defaults: { _controller: RockITTechgamesBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    path:   /logout

rock_it_techgames_homepage:
    pattern:  /
    defaults: { _controller: RockITTechgamesBundle:Default:index }

rock_it_techgames_about:
    pattern:  /about
    defaults: { _controller: RockITTechgamesBundle:Default:about }

rock_it_techgames_newsroom:
    pattern:  /newsroom
    defaults: { _controller: RockITTechgamesBundle:Default:newsroom }

rock_it_techgames_anouncements:
    pattern:  /announcements
    defaults: { _controller: RockITTechgamesBundle:Default:announcements }

game_detail:
    pattern:  /game/{gameId}
    defaults: { _controller: RockITTechgamesBundle:Game:detail }

game_edit:
    pattern:  /game/{gameId}/edit
    defaults: { _controller: RockITTechgamesBundle:Game:edit }

game_join:
    pattern:  /game/{gameId}/join
    defaults: { _controller: RockITTechgamesBundle:Game:join }


sponsor_overview:
    pattern:  /sponsors/
    defaults: { _controller: RockITTechgamesBundle:Sponsor:overview }

sponsor_detail:
    pattern:  /sponsors/{sponsorId}
    defaults: { _controller: RockITTechgamesBundle:Sponsor:detail }

profile_detail:
    pattern:  /profile/{profileId}
    defaults: { _controller: RockITTechgamesBundle:Profile:detail }

team_create:
    pattern:  /team/create
    defaults: { _controller: RockITTechgamesBundle:Team:create }

team_detail:
    pattern:  /team/{teamId}
    defaults: { _controller: RockITTechgamesBundle:Team:detail }

team_edit:
    pattern:  /team/{teamId}/edit
    defaults: { _controller: RockITTechgamesBundle:Team:edit }

school_detail:
    pattern:  /school/{schoolId}
    defaults: { _controller: RockITTechgamesBundle:School:detail }

teams_overview:
    pattern:  /teams
    defaults: { _controller: RockITTechgamesBundle:Team:overview }

admin_overview:
    pattern:  /admin
    defaults: { _controller: RockITTechgamesBundle:Admin:index }
