rock_it_techgames_homepage:
    pattern:  /
    defaults: { _controller: RockITTechgamesBundle:Default:index }

game_detail:
    pattern:  /games/{gameId}
    defaults: { _controller: RockITTechgamesBundle:Game:detail }

game_edit:
    pattern:  /games/{gameId}/edit
    defaults: { _controller: RockITTechgamesBundle:Game:edit }

game_join:
    pattern:  /games/{gameId}/join
    defaults: { _controller: RockITTechgamesBundle:Game:join }


sponsor_detail:
    pattern:  /sponsors/{sponsorId}
    defaults: { _controller: RockITTechgamesBundle:Sponsor:detail }

profile_detail:
    pattern:  /profiles/{profileId}
    defaults: { _controller: RockITTechgamesBundle:Profile:detail }

team_detail:
    pattern:  /teams/{teamId}
    defaults: { _controller: RockITTechgamesBundle:Team:detail }
