parameters:
#    rock_it_techgames.example.class: RockIT\TechgamesBundle\Example

services:
  rock_it_techgames.rockit_extension:
    class: RockIT\TechgamesBundle\Twig\Extension\RockITExtension
    tags:
      - { name: twig.extension }
  acme.twig.acme_extension:
    class: RockIT\TechgamesBundle\Twig\Extension\AcmeExtension
    tags:
      - { name: twig.extension2 }
  profileManager:
     class: RockIT\TechgamesBundle\Model\ProfileManager
  teamManager:
    class: RockIT\TechgamesBundle\Model\TeamManager
  gameManager:
    class: RockIT\TechgamesBundle\Model\GameManager
    arguments: ["@teamManager"]